version: '2' 
services:


  conda:
    build: conda
    hostname: py3dataconda
    container_name: docpyml-conda
    domainname: docpyml
    networks:
      - docpyml
    volumes:
      - ./data/shared:/shared
    ports:
      - "8888:8888"

  rocker:
    image: rocker/rstudio
    hostname: rocker
    container_name: docpyml-rocker
    domainname: docpyml
    networks:
      - docpyml
    volumes:
      - ./data/shared:/shared
    ports:
      - "8787:8787"   


  zeppelin:
    image: dylanmei/zeppelin
    hostname: zeppelin
    container_name: docpyml-zeppelin
    domainname: docpyml
    networks:
      - docpyml
    volumes:
      - ./data/shared:/shared
    ports:
      - "8081:8080"


networks:
  docpyml:
    external: true
